name: build-and-deploy-dev
on:
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}

jobs:
  main:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ github.run_id}}
      SERVICE: cloud-service
      REGION: us-central1
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # Authenticate to google
      - uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GKE_SA_KEY }}
      # Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      # Configure Docker to use the gcloud command-line tool as a credential
      # helper for authentication
      - run: |-
          gcloud --quiet auth configure-docker

      - uses: nrwl/nx-set-shas@v4
      - name: Install Nx
        run: npm install nx
      - name: Docker Login
        uses: docker/login-action@v1.6.0
        with:
          username: ${{ secrets.DOCKER_HUB_LOGIN }}
          password: ${{ secrets.DOCKER_HUB_SECRET }}
    #   - name: build images and push images
    #     run: docker buildx build --push --platform linux/amd64 -f apps/cloud-service/Dockerfile -t spartoine118/cloud-service:${{env.IMAGE_TAG}} .
    #   - name: Deploy to Cloud Run
    #     id: deploy
    #     uses: google-github-actions/deploy-cloudrun@v0
    #     with:
    #       service: ${{ env.SERVICE }}
    #       region: ${{ env.REGION }}
    #       image: spartoine118/cloud-service:${{env.IMAGE_TAG}}
    # NOTE: You can also set env variables here:
    #  env_vars: |
    #  NODE_ENV=production
    #  TOKEN_EXPIRE=6400
