name: build-and-deploy-dev
on:
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: spartoine118/cloud-service:11718396221
      SERVICE: cloud-function-dev
      REGION: us-central1
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # Authenticate to google
      - uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GKE_SA_KEY }}
      # Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GKE_PROJECT }}

      # Configure Docker to use the gcloud command-line tool as a credential
      # helper for authentication
      - run: |-
          gcloud --quiet auth configure-docker

      - uses: nrwl/nx-set-shas@v4
      - name: Docker Login
        uses: docker/login-action@v1.6.0
        with:
          username: ${{ secrets.DOCKER_HUB_LOGIN }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      # - name: build images and push images
      #   run: docker buildx build --push --platform linux/amd64 -f apps/cloud-service/Dockerfile -t spartoine118/cloud-service:${{env.IMAGE_TAG}} .

      - id: 'secrets'
        uses: 'google-github-actions/get-secretmanager-secrets@v2'
        with:
          secrets: |-
            SA_EMAIL:${{secrets.GKE_PROJECT}}/GKE_SA_EMAIL

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          image: spartoine118/cloud-service:${{env.IMAGE_TAG}}
          # NOTE: You can also set env variables here:
          env_vars: |-
            SERVICE_ACCOUNT_EMAIL=${{steps.secrets.outputs.SA_EMAIL}}
          flags: |
            --service-account=${{steps.secrets.outputs.SA_EMAIL}}
